/// Host-side scene description structures for feeding the WGPU compute pipeline.
///
/// These mirror the information generated by the CPU renderer (camera setup,
/// materials, voxel grid) but are designed to be populated directly from Rust
/// code instead of the Shape-Z DSL. The intent is to serialize these structures
/// into GPU buffers/textures before dispatching compute shaders.
/// Convenience alias for 3D vectors stored as floats.
pub type Vec3 = [f32; 3];

/// Describes the thin-lens camera used by the path tracer.
///
/// Values are expressed in world units. The aperture and focus distance fields
/// allow depth-of-field effects once the shader implementation is ready.
#[derive(Debug, Clone)]
pub struct Camera {
    pub origin: Vec3,
    pub target: Vec3,
    pub up: Vec3,
    pub vertical_fov_degrees: f32,
    pub aperture: f32,
    pub focus_distance: f32,
}

impl Default for Camera {
    fn default() -> Self {
        Self {
            origin: [4.0, 4.0, 4.0],
            target: [0.0, 0.0, 0.0],
            up: [0.0, 1.0, 0.0],
            vertical_fov_degrees: 45.0,
            aperture: 0.0,
            focus_distance: 5.0,
        }
    }
}

/// Material parameters consumed by the BSDF implementation on the GPU.
#[derive(Debug, Clone)]
pub struct Material {
    pub base_color: Vec3,
    pub emission: Vec3,
    pub roughness: f32,
    pub metallic: f32,
    /// 0 = default lambertian, 1 = dielectric, 2 = conductor, etc.
    pub shader_model: u32,
}

impl Default for Material {
    fn default() -> Self {
        Self {
            base_color: [0.8, 0.8, 0.8],
            emission: [0.0, 0.0, 0.0],
            roughness: 0.5,
            metallic: 0.0,
            shader_model: 0,
        }
    }
}

/// Minimal voxel payload matching the CPU tracer's expectations.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Voxel {
    pub material: u8,
    pub volumetric_id: Option<u8>,
}

/// Dense voxel volume storing `Voxel` values in Z-major order.
#[derive(Debug, Clone)]
pub struct VoxelVolume {
    pub dims: [u32; 3],
    voxels: Vec<Voxel>,
}

impl VoxelVolume {
    pub fn new(dims: [u32; 3]) -> Self {
        let len = dims[0] as usize * dims[1] as usize * dims[2] as usize;
        Self {
            dims,
            voxels: vec![Voxel::default(); len],
        }
    }

    #[inline]
    pub fn index(&self, x: u32, y: u32, z: u32) -> Option<usize> {
        if x < self.dims[0] && y < self.dims[1] && z < self.dims[2] {
            let idx = (z * self.dims[0] * self.dims[1]) + (y * self.dims[0]) + x;
            Some(idx as usize)
        } else {
            None
        }
    }

    pub fn set_voxel(&mut self, x: u32, y: u32, z: u32, voxel: Voxel) {
        if let Some(idx) = self.index(x, y, z) {
            self.voxels[idx] = voxel;
        }
    }

    pub fn get_voxel(&self, x: u32, y: u32, z: u32) -> Option<Voxel> {
        self.index(x, y, z).map(|idx| self.voxels[idx])
    }

    pub fn voxels(&self) -> &[Voxel] {
        &self.voxels
    }

    pub fn voxels_mut(&mut self) -> &mut [Voxel] {
        &mut self.voxels
    }
}

/// Global lighting properties such as background color and sun direction.
#[derive(Debug, Clone)]
pub struct Environment {
    pub background_color: Vec3,
    pub sun_direction: Option<Vec3>,
    pub sun_emission: Vec3,
}

impl Default for Environment {
    fn default() -> Self {
        Self {
            background_color: [0.8, 0.8, 0.9],
            sun_direction: None,
            sun_emission: [1.0, 0.95, 0.9],
        }
    }
}

/// Immutable scene description ready to be uploaded to GPU buffers.
#[derive(Debug, Clone)]
pub struct SceneDescription {
    pub camera: Camera,
    pub materials: Vec<Material>,
    pub volume: VoxelVolume,
    pub environment: Environment,
}

/// Builder API for assembling `SceneDescription` instances programmatically.
#[derive(Debug, Clone)]
pub struct SceneBuilder {
    camera: Camera,
    materials: Vec<Material>,
    environment: Environment,
    volume: VoxelVolume,
}

impl SceneBuilder {
    pub fn new(dims: [u32; 3]) -> Self {
        Self {
            camera: Camera::default(),
            materials: vec![Material::default()],
            environment: Environment::default(),
            volume: VoxelVolume::new(dims),
        }
    }

    pub fn camera(mut self, camera: Camera) -> Self {
        self.camera = camera;
        self
    }

    pub fn environment(mut self, environment: Environment) -> Self {
        self.environment = environment;
        self
    }

    pub fn materials(mut self, materials: Vec<Material>) -> Self {
        self.materials = materials;
        self
    }

    pub fn with_voxel<F>(mut self, mut f: F) -> Self
    where
        F: FnMut(&mut VoxelVolume),
    {
        f(&mut self.volume);
        self
    }

    pub fn build(self) -> SceneDescription {
        SceneDescription {
            camera: self.camera,
            materials: self.materials,
            environment: self.environment,
            volume: self.volume,
        }
    }
}
